### ISSUE TITLE
Scan vesting pallet business

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/statescan-v2#686]
[Vesting](https://github.com/paritytech/substrate/tree/master/frame/vesting) is a substrate pallet which provides a means of placing a linear curve on an account's locked balance. Information we should show on statescan includes:
- Vesting schedules statistics.
- List of all schedules happened on chain, including the schedule status, basic information.
- All vesting records.
- Vesting records against a account, a schedule.

Generally the coding work will includes:
1. Query from blockchain storage to get a account's vesting info.
2. Query blocks from chain RPC, and extract extrinsics/events for business handling. Already done to save bounty implementers' time.
3. Write code to handle events or extrinsics, and extract business data. You can find the vesting events and extrinsics [here](https://github.com/paritytech/substrate/blob/master/frame/vesting/src/lib.rs).
4. Normalize data and save them to MongoDB.

We have to extract business data to support following future user stories:
1. As a community user, I can see the vesting statistics data, so I can know how many schedules were created, and how many are still active.
2. As a vesting owner, I want to know how many vesting now I have and how much balance are total locked, and locked balance of each vesting.
3. As a vesting owner, I want to see my history vesting records.
4. As a vesting owner, I want to see the timeline of my any vesting, so I can know the details, like who gave me the `vested_transfer`, when I did `vest` calls, whether I once merged vestings.

Context:
1. The [vesting-scan](https://github.com/opensquare-network/statescan-v2/tree/main/backend/packages/vesting-scan) package has been initialized. Implementers should track the scan logic from [src/index.js](https://github.com/opensquare-network/statescan-v2/blob/main/backend/packages/vesting-scan/src/index.js).
2. Implementers can refer to other scan packages to learn the common logic how statescan scans blocks and extracts business.

Requirements for implementers:
1. Know the basic concepts of blockchain, like transactions, events, state, contract.
2. Has [Node.js](https://nodejs.org/en) programming experience.

Note:
- This bounty is funded by kusama treasury, and will be a child bounty of [kusama bounty #11](https://kusama.subsquare.io/treasury/bounty/11).
- [OpenSquare team](https://www.opensquare.network/team/) is the bounty curator and provide various guides. No worries if you think there are problems you may not be able to solve which will prevent your application.

**Comment by ruibinx** [comment]
Hi, I am applying for this bounty because I have the skills and experience to complete it successfully. I have the following qualifications:

- I am familiar with Rust and Substrate. I was responsible for Parami Blockchain, an open source project that leverages Substrate to create a decentralized advertising network. You can find the code at https://github.com/parami-foundation/parami-blockchain.
- I have experience with polkadot.js. I have created apps with polkadot.js(closed source).
- I am familiar with substrate chain events mechanism.
- I have years of experience in backend and big data development, which gives me a solid foundation in software engineering and data analysis.

I am confident that I can deliver a high-quality solution for this bounty within the given timeframe and budget. I am eager to start working on it and learn more about your project. Thank you for your consideration.

Contact me at: xingrobin#gmail.com

**Comment by wliyongfeng** [comment]
@ruibinx I've assigned you. Please accept it and join [OpenSquare element](https://matrix.to/#/#opensquare:matrix.org) or [OpenSquare telegram](https://t.me/opensquare) for future communication and collaboration. Please create a WIP pull request if you've started the implementation, so we can know the process and give some suggestions.

**Comment by ruibinx** [comment]
Thanks! I should be starting working on this by the weekend and will create a WIP pull request as soon as possible.
